### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by devanshudew** [dcordero/Rubustrings#11]
Devanshus:kplms devanshus$ sudo rubustrings Localizable.strings
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- colored (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/rubustrings-0.0.3/lib/rubustrings/action.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/rubustrings-0.0.3/lib/rubustrings.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/rubustrings-0.0.3/bin/rubustrings:3:in `<top (required)>'
	from /usr/local/bin/rubustrings:22:in `load'
	from /usr/local/bin/rubustrings:22:in `<main>'

**Comment by tungngodinh** [comment]
@devanshudew 
I run
`sudo gem install colored`
`\curl -sSL https://get.rvm.io | bash -s stable`
`source /Users/your account name/.rvm/scripts/rvm`
It works with me
Hope to help you

**Comment by core-code** [comment]
hit the same error, would be nice to mention the dependency in the readme

**Comment by dcordero** [comment]
Fixed on version 0.0.4. The dependencies will be now auto installed when installing Rubustrings via `gem install rubustrings`

Thanks for reporting

**Comment by core-code** [comment]
thanks!
