### ISSUE TITLE
good to have it auto-installs the colored gem when install this gem.

### ISSUE THREAD

**Issue by djwgit** [dcordero/Rubustrings#12]
good to have it auto-installs the colored gem when install this gem.
thanks for this useful tool.

**Comment by dcordero** [comment]
That is a great idea @djwgit  !! A pull request would be really appreciated

**Comment by djwgit** [comment]
ok, will play with the gem install thing, to see how the install dependency works ...
thanks @dcordero

**Comment by dcordero** [comment]
Fixed by https://github.com/dcordero/Rubustrings/pull/14
