### ISSUE TITLE
XCode 6.3 beta 2

### ISSUE THREAD

**Issue by danielgomezrico** [dcordero/Rubustrings#3]
I tried to run it over my file and it says:

`./rubustrings.rb:17:in`read': "\"d" on UTF-16 (Encoding::InvalidByteSequenceError)
    from ./rubustrings.rb:17:in `open_and_read_file'
    from ./rubustrings.rb:79:in`validate_localizable_string_file'
    from ./rubustrings.rb:94:in `block in <main>'
    from ./rubustrings.rb:92:in`each'
    from ./rubustrings.rb:92:in `<main>'`

**Comment by dcordero** [comment]
Seems like an issue regarding encoding @danielgomezrico I will take a look into it later, but at the moment if you need it, you can change this line.

```
 17   File.open(file_name, 'rb:utf-16:utf-8').read if File.exist?(file_name)
```

to be like this:

```
 17   File.open(file_name, 'r').read if File.exist?(file_name)
```

and it should start working as expected.

**Comment by dcordero** [comment]
Fixed https://github.com/dcordero/Rubustrings/pull/8
