### ISSUE TITLE
String argument position - incorrect validation error

### ISSUE THREAD

**Issue by deberle** [dcordero/Rubustrings#4]
The validation incorrectly fails when the argument position in the translation string is changed like so:

```
"%@, %@" = "%2$@ %1$@";
```

Example: 
en: "1, Infinite Loop"
de: "Infinite Loop 1"

I just tried to fix this, but I'm a complete regex dead-loss :(

**Comment by dcordero** [comment]
Hi @deberle,

thanks for the report. It is seems to be a issue regarding the format change, from %@ to %2$@ but nothing regarding the position. 

I will take a look into it !

**Comment by deberle** [comment]
Thanks for the response, and btw thanks for this very helpful tool! 

So actually another example would be: 

```
"%1$@, %2$@" = "%2$@ %1$@";
```

Here's some documentation from apple: 
https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html

> One problem that often occurs during translation is that the translator may need to reorder parameters inside translated strings to account for differences in the source and target languages. If a string contains multiple arguments, the translator can insert special tags of the form n$ (where n specifies the position of the original argument) in between the formatting characters. These tags let the translator reorder the arguments that appear in the original string. The following example shows a string whose two arguments are reversed in the translated string:
> 
>    /\* Message in alert dialog when something fails */
>     "%@ Error! %@ failed!" = "%2$@ blah blah, %1$@ blah!";

**Comment by rliljest** [comment]
Also might need to strip out % literal formats, e.g.

```
"BATTERY_PERCENTAGE_%d" = "Battery at %d%%";
```
